#!/bin/sh

# This script downloads the networktables binaries approriate for the system
# where it is run

# It should work on amd64 systems and Rasberry Pi's

mkdir -p lib

jarfile="lib/networktables.jar"

if [ ! -s "$jarfile" ]
then
  if [ "$(uname -m | cut -c -3)" = "arm" ]
  then
    nturl="http://first.wpi.edu/FRC/roborio/maven/release/edu/wpi/first/wpilib/networktables/java/NetworkTables/3.1.7/NetworkTables-3.1.7-arm-raspbian.jar"
  else
    nturl="http://first.wpi.edu/FRC/roborio/maven/release/edu/wpi/first/wpilib/networktables/java/NetworkTables/3.1.7/NetworkTables-3.1.7-desktop.jar"
  fi
  curl -o "$jarfile" "$nturl"
fi

ant build

